/*
 * RdmaHeader_m.h
 *
 *  Created on: Aug 10, 2021
 *      Author: vr4
 */

#ifndef INET_TRANSPORTLAYER_RDMA_RDMAHEADER_M_H_
#define INET_TRANSPORTLAYER_RDMA_RDMAHEADER_M_H_

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class RdmaHeader;
} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/transportlayer/common/CrcMode_m.h" // import inet.transportlayer.common.CrcMode

#include "inet/transportlayer/contract/TransportHeaderBase_m.h" // import inet.transportlayer.contract.TransportHeaderBase

// cplusplus {{
#include "inet/common/INETUtils.h"
#include "inet/clock/contract/ClockTime.h"
// }}


namespace inet {

// cplusplus {{
const B RDMA_HEADER_LENGTH = B(8);
// }}

/**
 * Class generated from <tt>inet/transportlayer/rdma/RdmaHeader.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // Represents an Rdma header, to be used with the ~Rdma module.
 * //
 * class RdmaHeader extends TransportHeaderBase
 * {
 *     unsigned short srcPort;
 *     unsigned short destPort;
 *     chunkLength = RDMA_HEADER_LENGTH;
 *     B totalLengthField = B(-1);   // RDMA header + payload in bytes
 *     uint16_t crc \@toString(utils::hex($)) \@fromString(utils::uhex($)) = 0;
 *     CrcMode crcMode = CRC_MODE_UNDEFINED;
 *     int dstAddress;//Cambiado
 * }
 * </pre>
 */
class INET_API RdmaHeader : public ::inet::TransportHeaderBase
{
  protected:
    unsigned short srcPort = 0;
    unsigned short destPort = 0;
    B totalLengthField = B(-1);
    uint16_t crc = 0;
    inet::CrcMode crcMode = CRC_MODE_UNDEFINED;
    clocktime_t generationTime;
    clocktime_t receptionTime;

  private:
    void copy(const RdmaHeader& other);

  protected:
    bool operator==(const RdmaHeader&) = delete;

  public:
    RdmaHeader();
    RdmaHeader(const RdmaHeader& other);
    virtual ~RdmaHeader();
    RdmaHeader& operator=(const RdmaHeader& other);
    virtual RdmaHeader *dup() const override {return new RdmaHeader(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual unsigned short getSrcPort() const;
    virtual void setSrcPort(unsigned short srcPort);
    virtual unsigned short getDestPort() const;
    virtual void setDestPort(unsigned short destPort);
    virtual B getTotalLengthField() const;
    virtual void setTotalLengthField(B totalLengthField);
    virtual uint16_t getCrc() const;
    virtual void setCrc(uint16_t crc);
    virtual inet::CrcMode getCrcMode() const;
    virtual void setCrcMode(inet::CrcMode crcMode);
    virtual clocktime_t getGenerationTime() const;
    virtual void setGenerationTime(clocktime_t generationtime);

  public:
    virtual unsigned int getSourcePort() const override { return getSrcPort(); }
    virtual void setSourcePort(unsigned int port) override { setSrcPort(port); }
    virtual unsigned int getDestinationPort() const override { return getDestPort(); }
    virtual void setDestinationPort(unsigned int port) override { setDestPort(port); }
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RdmaHeader& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RdmaHeader& obj) {obj.parsimUnpack(b);}

} // namespace inet



#endif /* INET_TRANSPORTLAYER_RDMA_RDMAHEADER_M_H_ */
